# Waits
implicit.wait=10
explicit.wait=20
polling.interval=500

# LLM Configuration
llm.provider=LM_STUDIO

lmstudio.url=http://127.0.0.1:1234

lmstudio.enable.fallback=false

lmstudio.model=qwen/qwen2.5-vl-7b

#openai.api.key=

# Browser Configuration
browser=chrome
headless=true
